### ISSUE TITLE
UITextView 的 placeholder 的文字颜色与默认的不一致

### ISSUE THREAD

**Issue by shiweifu** [Huohua/HHKit#4]
代码中：
      self.placeholderLabel.textColor = [UIColor grayColor];
      self.placeholderLabel.alpha = 0.7f;

与默认的 placeholder 的颜色不一致，和 UITextField 放在一起看很明显颜色重一些。

我用这种方式设置：
    self.placeholderLabel.textColor = [UIColor colorWithRed:0 green:0 blue:0.1 alpha:0.22];

相对来说更一致。

**Comment by Cee** [comment]
感谢提醒。

文档中对于 `attributedPlaceholder` 这个 property 有以下的说明：
> This property is nil by default. If set, the placeholder string is drawn using a 70% grey color and the remaining style information (except the text color) of the attributed string.
